README.md

The TOC was not being rendered in README.md.

Added TOC in README.md

---

glazier/lib/actions/README.md
glazier/lib/actions/__init__.py
glazier/lib/actions/file_system.py
glazier/lib/actions/file_system_test.py

Implement CopyDir action.

---

glazier/lib/policies/__init__.py

Internal change

---

glazier/lib/actions/file_system.py

Add argument to allow deleting the destination folder if it already exists when running CopyDir action.

Add argument to allow deleting the destination folder if it already exists when running CopyDir action.

---

glazier/lib/actions/README.md

Add examples for CopyDir in Glazier README

Add examples for CopyDir in Glazier README

---

glazier/lib/log_copy_test.py

Support PY3 modifications to gwinpy/registry in log_copy_test.

Support PY3 modifications to gwinpy/registry in log_copy_test.

---

README.md

Update README to set support expectations

Update README to set support expectations

---

README.md

Fix badge rendering on github

---

glazier/lib/download.py
glazier/lib/download_test.py

Automated g4 rollback of changelist 264182653.
*** Reason for rollback ***
want further review
*** Original change description ***

Automated g4 rollback of changelist 264182653.

---

README.md

Summarize main Glazier README 'how it works'

Summarize main Glazier README 'how it works'

---

glazier/lib/actions/files.py
glazier/lib/actions/files_test.py

Specify PY3-friendly string encoding

Specify PY3-friendly string encoding

---

glazier/lib/googet.py

Swap order of cmd and max_attempts

Swap order of cmd and max_attempts

---

glazier/lib/interact.py
glazier/lib/interact_test.py

python 3 support for detecting keystrokes

python 3 support for detecting keystrokes

---

doc/setup/README.md

Update setup documentation to reference powershell rather than batch files.

Update setup documentation to reference powershell rather than batch files.

---

doc/setup/README.md
doc/setup/about.md

Replace startnet.cmd references with winpeshl

Replace startnet.cmd references with winpeshl

---

glazier/lib/stage.py
glazier/lib/stage_test.py

Partial implementation of build stages to track Glazier progress.

Partial implementation of build stages to track Glazier progress.

---

glazier/lib/actions/README.md
glazier/lib/actions/installer.py
glazier/lib/actions/installer_test.py

Add an action for setting the build stage.

Add an action for setting the build stage.

---

glazier/lib/actions/timers.py
glazier/lib/actions/timers_test.py

Add functionality to write timers to registry for all completed actions.

Add functionality to write timers to registry for all completed actions.

---

glazier/lib/stage.py
glazier/lib/stage_test.py

Adding stage active time to determine the duration of the current active stage (if any).

Adding stage active time to determine the duration of the current active stage (if any).

---

glazier/lib/actions/googet.py
glazier/lib/googet.py
glazier/lib/stage.py

Scrub TODOs with bugs and usernames from github

Scrub TODOs with bugs and usernames from github

---

glazier/lib/bitlocker.py
glazier/lib/buildinfo.py
glazier/lib/cache.py
glazier/lib/file_util.py

Add type hints to bitlocker.py, cache.py, & file_util.py.

Add type hints to bitlocker.py, cache.py, & file_util.py.

---

glazier/lib/buildinfo.py
glazier/lib/googet.py

Add partial type checking to buildinfo and googet libraries.

Add partial type checking to buildinfo and googet libraries.

---

glazier/lib/buildinfo.py
glazier/lib/buildinfo_test.py

Implement functools.lru_cache to cache some buildinfo results.

Implement functools.lru_cache to cache some buildinfo results.

---

go/eventlog/eventlog.go

Hi,
This enables the use of the ExportLog feature implemented in wevtapi.
Thanks.

Add support for EvtExportLog
